name: crypton
description: A simple Dart library for asymmetric encryption and digital signatures
version: 1.1.2
homepage: https://github.com/konstantinullrich
repository: https://github.com/konstantinullrich/crypton
issue_tracker: https://github.com/konstantinullrich/crypton/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.0
  asn1lib: ^0.8.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
