name: crypton
description: A simple Dart library for asymmetric encryption and digital signatures
version: 2.0.0-nullsafety
homepage: https://github.com/konstantinullrich
repository: https://github.com/konstantinullrich/crypton
issue_tracker: https://github.com/konstantinullrich/crypton/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  pointycastle: ^3.0.0-nullsafety.2
  asn1lib: ^0.9.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
